defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Your Name Website
subtitle: Further Digital Fabrication & Prototyping
baseurl: "/EP1001-template"  # update the subpath of your site, e.g. /blog
# theme: panthera-jekyll
remote-theme: christianezeani/panthera-jekyll

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: About
    link: /about.html
    icon: ""

  - text: Introduction & Digital Fabrication Skills Review
    link: /docs/01-intro.html
    icon: ""

  - text: Electronics Production
    link: /docs/02-elecProd.html
    icon: ""

  - text: Electronics Design
    link: /docs/03-elecDesign.html
    icon: ""

  - text: 2D Large Format Machining
    link: /docs/04-2drouting.html
    icon: ""

  - text: Embedded Programming
    link: /docs/05-embedded.html
    icon: ""

  - text: Molding & Casting
    link: /docs/06-moldcast.html
    icon: ""

  - text: 3D Machining
    link: /docs/07-3dmachining.html
    icon: ""

  - text: Interface & Application Programming
    link: /docs/08-applicationsProg.html
    icon: ""

  - text: Final Project
    link: /docs/09-project.html
    icon: ""

  - text: Contact
    link: /contact.html
    icon: ""


# Socialmedia Icons
social_icons:
  - name: linkedin
    link: ""
    icon: fab fa-linkedin

  - name: github
    link: ""
    icon: fab fa-github-square

  - name: facebook
    link: ""
    icon: fab fa-facebook-square

  - name: twitter
    link: ""
    icon: fab fa-twitter
